/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cosinesimilarity;

import static cosinesimilarity.CosineSimilarity.Tokenized_comment;
import static cosinesimilarity.CosineSimilarity.similarity_to_doc1;
import static cosinesimilarity.CosineSimilarity.similarity_to_doc2;
import static cosinesimilarity.FindingTermandDocumentFrequency.frq2;
import static cosinesimilarity.PreparingForCosineSimilarity.Doc1;
import static cosinesimilarity.PreparingForCosineSimilarity.Doc2;
import static cosinesimilarity.PreparingForCosineSimilarity.Query;

/**
 *
 * @author Rajib-pc
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Submitbuttin = new javax.swing.JButton();
        Output = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        InputQuery = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Siyam Rupali", 1, 14)); // NOI18N
        jLabel1.setText("কিছু লিখুনঃ");

        jLabel2.setFont(new java.awt.Font("Siyam Rupali", 1, 14)); // NOI18N
        jLabel2.setText("অনুভুতিঃ");

        jLabel3.setFont(new java.awt.Font("Siyam Rupali", 1, 24)); // NOI18N
        jLabel3.setText("        অনুভূতি বিশ্লেষণ (বাংলা)");

        Submitbuttin.setFont(new java.awt.Font("Siyam Rupali", 1, 14)); // NOI18N
        Submitbuttin.setText("দাখিল করুন");
        Submitbuttin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttinActionPerformed(evt);
            }
        });

        Output.setFont(new java.awt.Font("Siyam Rupali", 1, 14)); // NOI18N
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        InputQuery.setColumns(20);
        InputQuery.setFont(new java.awt.Font("Siyam Rupali", 1, 14)); // NOI18N
        InputQuery.setRows(5);
        jScrollPane2.setViewportView(InputQuery);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Output))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Submitbuttin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Submitbuttin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed

    }//GEN-LAST:event_OutputActionPerformed

    private void SubmitbuttinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttinActionPerformed
        
        String aa = InputQuery.getText();
        aa = " " + aa;
        CosineSimilarity c = new CosineSimilarity();
        c.MainMethod(aa);

        if (similarity_to_doc2 > similarity_to_doc1) {
            Output.setText("ইতিবাচক");
        } else {
            Output.setText("নেতিবাচক");
        }
        
        QueryTermandDocumentFrequency.QueryTF.clear();
        QueryTermandDocumentFrequency.QueryDF.clear();
        QueryTermandDocumentFrequency.QueryIDF.clear();
        QueryTermandDocumentFrequency.uniquefrq3.clear();
        QueryTermandDocumentFrequency.frq3.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.NegativeDF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.NegativeIDF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.NegativeTF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.PositiveDF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.PositiveIDF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.PositiveTF.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.frq1.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.uniquefrq1.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.uniquefrq2.clear();
        cosinesimilarity.FindingTermandDocumentFrequency.frq2.clear();
        Tokenized_comment.clear();
        Doc1.clear();
        Doc2.clear();
        Query.clear();
        
//        Output.setText("");
    }//GEN-LAST:event_SubmitbuttinActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InputQuery;
    private javax.swing.JTextField Output;
    private javax.swing.JButton Submitbuttin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
